### ISSUE TITLE
Remove sudo from .travis.yml

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/pcds-ci-helpers#14]
Sudo was removed [awhile ago](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

While at it, we might as well also add `os: linux`, `dist: xenial`, and change `matrix` to `jobs` to get rid of the rest of the infos in our build config validation:

![Screen Shot 2020-04-09 at 8 06 03 PM](https://user-images.githubusercontent.com/6636512/78958666-a252a200-7a9d-11ea-828b-b783320cc624.png)

**Comment by klauer** [comment]
Sounds good - also should update https://github.com/pcdshub/cookiecutter-pcds-python/blob/master/%7B%7B%20cookiecutter.folder_name%20%7D%7D/.travis.yml

**Comment by hhslepicka** [comment]
Sudo was removed with the new shared configuration.
