### ISSUE TITLE
ENH: Add python build docs script

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/pcds-ci-helpers#20]
The example `.travis.yml` has a `BUILD_DOCS=1` job but this is not used in `init.sh` at all.
https://github.com/pcdshub/pcds-ci-helpers/blob/0aad202cd9086cb79a4b6dbadab94281893000ca/example_python_travis.yml#L23-L24
There is a script for Twincat build docs, but not for python as far as I can see.
It looks like the Twincat one also has some special arguments so I guess it wouldn't be good to merge them into a single script?

**Comment by klauer** [comment]
I think a good path forward would be to use @hhslepicka 's separate yaml format: https://github.com/hhslepicka/pcds-ci-helpers/tree/pypi

I think that effort may be stalled (@hhslepicka?) so maybe you could pick it up, @ZryletTC as you're on a roll with this stuff.

**Comment by hhslepicka** [comment]
It is for sure stalled... 😭 😞 @ZryletTC if you would like to take it over I can walk you through it early next week...

**Comment by ZryletTC** [comment]
> It is for sure stalled... 😭 😞 @ZryletTC if you would like to take it over I can walk you through it early next week...

Sure, that sounds good. Thanks :)
