### ISSUE TITLE
Conda builds need to be tested too

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/pcds-ci-helpers#23]
One large thing I didn't catch on the first review: this PR introduces conda build + upload, but only has pip-based requirement testing.

For historical (well, practical) reasons, PCDS repositories have put conda support first, with pip/pypi and the associated requirements files remaining second-class citizens. That means that solely testing with `pip` based requirements files does not give us the full picture.

Regardless of the above, I think there should probably be 2 test paths.
1. Conda
   a. conda build (using `meta.yaml`, of course)
   b. test
   c. conda upload
2. pip
   a. pip install
   b. test (same as conda test)
   c. pypi upload

This could be done in a follow-up PR or as an extension to this one, if you like.

_Originally posted by @klauer in https://github.com/pcdshub/pcds-ci-helpers/pull/22#issuecomment-628087815_

**Comment by ZryletTC** [comment]
Also make sure `pip install --upgrade pip` is added to pip tests.

**Comment by ZryletTC** [comment]
Keep #2 in mind when writing this.

**Comment by klauer** [comment]
I think this has been accounted for by @ZryletTC and @hhslepicka - closing.
