### ISSUE TITLE
Current .travis.yml is broken

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/pcds-ci-helpers#26]
Further than #6, the way `.travis.yml` is currently written, `init.sh` fails because the repository is cloned first so there is no `pcds-ci-helpers` directory to pushd into. It looks like this is failing somewhat quietly and the builds have been reporting successful completions anyway. This has been happening since #19, I guess none of us actually checked the job log 😞 

Does running `init.sh` on this repository actually do anything for us?
If so, we should add a `cd ..` or a `git clone...` or something to allow it to actually run.
If not, I guess we can just get rid of the last few lines of `.travis.yml`

If anyone figures out why the jobs pass even with the pushd error, I'm very curious.

**Comment by klauer** [comment]
Looks like it's only for checking pre-commit.

I think this passes only because we're lucky: https://travis-ci.org/github/pcdshub/pcds-ci-helpers/jobs/688594571#L181

`pushd` is trying to get to the pcds-ci-helpers directory, and it just so happens that that is also the directory travis starts out at.

Something like:
```
git clone https://github.com/pcdshub/pcds-ci-helpers/ pcds-ci-helpers
cd pcds-ci-helpers

pushd pcds-ci-helpers   # <-- fails, but that's ok
source travis/init.sh   # continues as expected
```

**Comment by ZryletTC** [comment]
Ahh, I think don't think Travis sees the error because it occurs within the sourced script and it is only looking at the exit code of the whole script, which is the exit code of the last command.

**Comment by klauer** [comment]
It's possible we should have `set -e` for it to bail on the first error 🤷‍♂️

**Comment by ZryletTC** [comment]
Ahh, I misread. I was thinking the pre-commit checks were outside of `.init.sh`. So yeah, I guess the only real error is when it tries to `pushd pcds-ci-helpers` and it's ok if that fails. It'd just be nice if it didn't :)

**Comment by klauer** [comment]
Soon enough we can probably remove `init.sh` altogether. Its goal was to approximate what you've done (by way of "Set variable in a matrix and run one script"), without realizing travis could do it easier and better.

**Comment by hhslepicka** [comment]
Is this still valid?

**Comment by ZryletTC** [comment]
It was never really a big deal as the build still works. When I created the issue, I didn't realize that the build was still running the pre-commit script properly. I was mainly concerned with the small `No such file or directory` that was actually fine to ignore. The best solution to this is a solution to #27, so this issue can be closed in favor of that one.
