### ISSUE TITLE
Updated sample Python travis template (standard-python-conda.yml)

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-ci-helpers#32]
Ideally with inline comments explaining what needs to be done:
```
    # Set CONDA_EXTRAS for...
    - CONDA_EXTRAS="pip pyqt=5 happi"
```

**Comment by klauer** [comment]
While you're at it, @hhslepicka, could you update https://github.com/pcdshub/cookiecutter-pcds-python/blob/master/%7B%7B%20cookiecutter.folder_name%20%7D%7D/.travis.yml as well?

**Comment by hhslepicka** [comment]
Sure!
