### ISSUE TITLE
PyPI testing after 'build' stage

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-ci-helpers#33]
'build' stage is used to build the conda recipe
'test' stage is used to test based on that recipe

PyPI-based testing does not need to wait for the 'build' stage to complete. Is there a way it could be in its own parallel stage to 'build'?

**Comment by ZryletTC** [comment]
While it's not possible to have two different stages run in parallel, they could be put together in a stage that runs before the 'test' stage. The hardest challenge would then be to figure out what to call this pre-test test/build stage.

**Comment by hhslepicka** [comment]
It seems like a good idea due to the fact that the conda build takes long.
Name-wise I don't have a problem with it being called `build` but we can call it anything else.
I will submit a PR with this change and we can debate there.
