### ISSUE TITLE
Requirements files (pip-style) are used for conda

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-ci-helpers#40]
There are package naming differences between conda and PyPI, making this usage a problem.

Take, for example, a requirement of `PyQt5` in `requirements.txt`:
* `pip install --file requirements.txt` will succeed
* `conda install --file requirements.txt` will fail, as it expects `pyqt>=5`

"Fixing" either of these to be the other way will either cause (1) pip to fail (2) conda to fail or (3) the requirements comparison tool to fail. Adding this in the 'EXTRAS' section is not sufficient.

An appropriate fix would be to _always_ rely on the `meta.yaml` (similar to what I had proposed in #35) for conda requirements, and _always_ rely on the `*requirements*.txt` files for pip.

**Comment by hhslepicka** [comment]
I think `PyQt` is the only PITA that we have with this kind of situation...
Maybe I misunderstood #35. Is it the idea of it to get rid of the `*requirements*.txt` and having them always autogenerated via the requirements from `meta.yml`?

**Comment by klauer** [comment]
This is no longer an issue with GitHub Actions.
We use the conda recipe for build/install/test requirements for conda tests.
We use `*.txt` for pip-based testing.
