### ISSUE TITLE
pypi uploads failing at tag

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-ci-helpers#50]
See https://travis-ci.com/github/pcdshub/pcdsdevices/jobs/388797786

**Comment by klauer** [comment]
For reference: https://github.com/pcdshub/pcds-ci-helpers/blob/master/travis/shared_configs/pypi-upload.yml

Unclear if this is a travis thing or an us-thing; from the log:

```
rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
invalid option "--password="
failed to deploy
```

That said, we don't have `PYPI_TOKEN` set in our travis-ci config for pcdsdevices...

**Comment by klauer** [comment]
This is for Travis CI - if we still have problems with GitHub Actions and pypi we'll have to make a new issue.
