### ISSUE TITLE
Add twincat project style check

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-ci-helpers#9]
Take it from https://github.com/pcdshub/lcls-twincat-motion/pull/38

But also note that it's missing `.TcGVL` (and maybe others?)

**Comment by ZLLentz** [comment]
We also need to make sure we can configure exactly which files get style checked on a per-repository basis

**Comment by ZLLentz** [comment]
Other things to do at the same time:
- Fix tab check to only convert leading tabs
- Add a check and fix for the various unreadable XML files (NC config, startup config, TMC)

**Comment by klauer** [comment]
I stumbled on this the other day, not sure if you've seen it:

https://coala.io/#/home?lang=Python

Which can be customized in different ways, not necessarily just for Python:
https://docs.coala.io/en/release-0.6/Users/Tutorials/Self_Correcting_Bears.html

I think this is almost certainly overkill and an unnecessary dependency, but thought I'd share regardless.

**Comment by ZLLentz** [comment]
I object on the basis of the koala bears pun alone

Just kidding, looks neat

**Comment by ZLLentz** [comment]
Also sliding this link from slack into the thread: https://pre-commit.com/

**Comment by ZLLentz** [comment]
One more thought:

It was really nice to have the check and fix scripts within the repo with no dependencies attached and we're going to lose that by centralizing. I'm thinking about the best way to implement a tiny stub script that clones ci helpers and runs the style fixer, hitting and skipping exactly the same files as the travis check...

**Comment by ZLLentz** [comment]
I'm going to pursue the "automatically fix errors in a centralized way" idea in the pre-commit repo. The rest has been mostly addressed by #11 and #15, but this should be revisited one last time when we have an xml formatter set up in the pre-commit repo. After that it will be fair to require the .tmc, NC config, and CoE startup files to be formatted neatly.

**Comment by ZLLentz** [comment]
This is somewhat closed by #18 unless we want to write a redundant xml formatting check
